### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ratbtch** [zenwarr/vk-dialogue-export#2]
![download](https://user-images.githubusercontent.com/34887477/39735509-f0788fd6-5249-11e8-97b7-e5eacc0b19b3.png)

**Comment by ratbtch** [comment]
Попробовал еще раз
![download](https://user-images.githubusercontent.com/34887477/39851897-a4a72bae-53e7-11e8-85d9-d44009b17b91.png)

**Comment by Stat1cV01D** [comment]
@ratbtch  
Попробуйте мой фикс.
