### ISSUE TITLE
Script asks for a token even though it is already in the config.ini

### ISSUE THREAD

**Issue by nesvoboda** [zenwarr/vk-dialogue-export#5]
I've started the script both with login/password and without them, added my token/user id, but it still asks me to provide the token and doesn't start.
Running on Python 3.6, OS X, x64

**Comment by nesvoboda** [comment]
Workaround: add token and user id in code

**Comment by zenwarr** [comment]
Can't replicate, did you remove `;` before the lines in `config.ini`?

**Comment by nesvoboda** [comment]
@zenwarr not really. I suppose that's the problem. Thank you!
