### ISSUE TITLE
Бесконечная авторизация

### ISSUE THREAD

**Issue by NecroBoy** [zenwarr/vk-dialogue-export#8]
![screenshot_7](https://user-images.githubusercontent.com/15165404/44164757-3d994580-a10a-11e8-8e89-d7677a9033b7.png)
Данные рабочие, через них авторизируется в APIdog
Раньше всё работало по токену, сейчас не хочет

**Comment by zenwarr** [comment]
У токена точно есть права на доступ к сообщениям? Возможно, токен из другого приложения, авторизация проходит нормально, судя по скрину, ошибка во время попытки доступа к сообщениям.
